name: API Testing Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '00 22 * * *'     # 6 PM EST
    - cron: '00 14 * * 1-5'   # 10 AM EST Monday to Friday

jobs:
  run-postman-tests:
    runs-on: ec2-github-runner

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Node and NPM
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Newman and HTML Extra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run the Postman Collection
        run: |
          mkdir -p newman
          newman run collectionCSV.json \
            -e env.json \
            -d data.csv \
            -r cli,htmlextra \
            --reporter-htmlextra-export newman/index.html

      - name: Upload Newman Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman/report.html


      - name: Creating github page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/

      - name: Send Email
        if: always()
        uses: dawidd6/action-send-mail@v16
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: API Test Execution Report
          to: patelrnk07@gmail.com,patelronak007@rocketmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
                Hello Everyone,
                API Testing Postman excution has been completed. The report has been published and url is: https://rnk07.github.io/APITesting-Postman/

                Thank you.
        
        
